/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxinteg.h
 *  model: ControlledTemperature_2
 *  expmt: ControlledTemperature_2
 *  date:  June 19, 2017
 *  time:  4:45:33 PM
 *  user:  Controllab Internal
 *  from:  Controllab Products B.V., 20-sim 4.7 Professional Single
 *  build: 4.7.1000.7863
 **********************************************************/

/* This file describes the integration methods
that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   * Vode Adams
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

#ifndef XX_INTEG_H
#define XX_INTEG_H

/* 20-sim include files */
#include "xxtypes.h"
#include "xxmodel.h" /* For the xx_ModelInstance typedef */

/* the integration methods */
XXBoolean XXRungeKutta4Initialize (xx_ModelInstance* model_instance);
XXBoolean XXRungeKutta4Terminate (xx_ModelInstance* model_instance);
XXBoolean XXRungeKutta4Step (xx_ModelInstance* model_instance, XXDouble outputTime);

#endif

