/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  src\xxsubmod.h
 *  subm:  ControlledTemperature
 *  model: ControlledTemperature_2
 *  expmt: ControlledTemperature_2
 *  date:  June 19, 2017
 *  time:  4:45:33 PM
 *  user:  Controllab Internal
 *  from:  Controllab Products B.V., 20-sim 4.7 Professional Single
 *  build: 4.7.1000.7863
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef XX_SUBMOD_H
#define XX_SUBMOD_H

/* Our own include files */
#include "xxmodel.h"



/* The submodel functions */
XXBoolean XXInitializeSubmodel (xx_ModelInstance* model_instance);
XXBoolean XXCalculateSubmodel (xx_ModelInstance* model_instance, XXDouble t, XXDouble outputTime);
XXBoolean XXTerminateSubmodel (xx_ModelInstance* model_instance, XXDouble t);

#endif

